name: diego
favicon: null
layout_spectrum: 0.7283413866534829
typography_spectrum: 0.9941921457648277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f1da15'
    - '#ada89b'
    - '#6f3540'
    - '#ab022b'
  brandStrength: 0.5
  lightness: 0.5789389684796333
  saturation: 0.4375
  rhythmicContrast: 0.005285779479891062
purpose: []
