name: diego
favicon: null
layout_spectrum: 0
typography_spectrum: 0.65315
title: Diego Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#134e7f'
    - '#abd476'
    - '#00ff00'
    - '#ffff00'
  brandStrength: 1
  lightness: 0.5789389684796333
  saturation: 0.4375
  rhythmicContrast: 0.005285779479891062
purpose: []
